version: '3'
services:
  postgres:
    image: "postgres:16.1-alpine"
    ports:
      - "${APP_DB_PORT}:${APP_DB_PORT}"
    environment:
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
      POSTGRES_DB: ${APP_DB_NAME}
      PGPORT: ${APP_DB_PORT}
